const WAIT_FOR_SKILL = 'WAIT_FOR_SKILL';
const WAIT_FOR_DISTANCE = 'WAIT_FOR_DISTANCE';
const WAIT_FOR_LEVELS = 'WAIT_FOR_LEVELS';
const WAIT_FOR_RESPONSE = 'WAIT_FOR_RESPONSE';
const WAIT_FOR_FORWARD_END = 'WAIT_FOR_FORWARD_END';
const WAIT_FOR_START = 'WAIT_FOR_START';
const WAIT_FOR_PIP_FORWARD = 'WAIT_FOR_PIP_FORWARD';
const WAIT_FOR_DATA_VALIDATION = 'WAIT_FOR_DATA_VALIDATION';
const WAIT_FOR_DATA_TO_PROCESS = 'WAIT_FOR_DATA_TO_PROCESS';
const WAIT_FOR_BUTTONS_AMOUNT = 'WAIT_FOR_BUTTONS_AMOUNT';

const states = {
  WAIT_FOR_SKILL,
  WAIT_FOR_DISTANCE,
  WAIT_FOR_LEVELS,
  WAIT_FOR_RESPONSE,
  WAIT_FOR_START,
  WAIT_FOR_FORWARD_END,
  WAIT_FOR_PIP_FORWARD,
  WAIT_FOR_DATA_VALIDATION,
  WAIT_FOR_DATA_TO_PROCESS,
  WAIT_FOR_BUTTONS_AMOUNT,
};

module.export = states;
