const weapon = [
    {
        icon: false,
		title: "Бейсбольная бита",
        cost: { materials: 30, },
        amount: 1,
        place: "🏚Торгаш",
    },
    {
        icon: false,
		title: "Ржавый нож",
        cost: { materials: 30, },
        amount: 3,
        place: "🏚Торгаш",
    },
    {
        icon: false,
		title: "Разводной ключ",
        cost: { materials: 30, },
        amount: 5,
        place: "🏚Торгаш",
    },
    {
        icon: false,
		title: "Топор",
        cost: { materials: 30, },
        amount: 7,
        place: "🏚Торгаш",
    },
    {
        icon: false,
		title: "Кинжал",
        cost: { materials: 30, },
        amount: 9,
        place: "🏚Торгаш",
    },
    {
        icon: false,
		title: "Мачете",
        cost: { materials: 30, },
        amount: 11,
        place: "🏚Торгаш",
    },
    {
        icon: false,
		title: "Хлыст",
        cost: { materials: 30, },
        amount: 13,
        place: "🏚Торгаш",
    },
    {
        icon: false,
		title: "Стальная бита",
        cost: { materials: 30, },
        amount: 16,
        place: "🏚Торгаш",
    },
    {
        icon: "⚡",
		title: "⚡️Прочная бита",
        cost: { materials: 200, },
        amount: 2,
        place: "🛠Верстак",
    },
    {
        icon: "⚡",
		title: "Копье",
        cost: { materials: 600, },
        amount: 4,
        place: "🛠Верстак",
    },
    {
        icon: "⚡",
		title: "⚡Кистень",
        cost: { materials: 1300, },
        amount: 6,
        place: "🛠Верстак",
    },
    {
        icon: "⚡",
		title: "Электромеч",
        cost: { materials: 3900, },
        amount: 9,
        place: "🛠Верстак",
    },
    {
        icon: "💥",
		title: "Лазерный тесак",
        cost: {
            materials: 5600,
            quartz: 4,
        },
        amount: 12,
        place: "🛠Верстак",
    },
    {
        icon: "💥",
		title: "BFGzzv-4000",
        cost: {
            materials: 12000,
            quartz: 30,
        },
        amount: 20,
        place: "🛠Верстак",
    },
    {
        icon: "💥",
		title: "BFGzzv-4000",
        cost: {
            materials: 12000,
            quartz: 30,
        },
        amount: 20,
        place: "🛠Верстак",
    },
    {
        icon: "🔗",
		title: "Силовой кастет",
        cost: {
            materials: 14000,
            quartz: 20,
            generators: 5,
        },
        amount: 25,
        place: "🛠Верстак",
    },
    {
        icon: "💥",
		title: "Колыбель Пустоши",
        cost: {
            materials: 19990,
            quartz: 35,
            generators: 5,
        },
        amount: 29,
        place: "🛠Верстак",
    },
    {
        icon: "💥",
		title: "Tyrant-PDR",
        cost: {
            materials: 29990,
            quartz: 60,
            generators: 25,
        },
        amount: 38,
        place: "🛠Верстак",
    },
    {
        icon: "☄️",
		title: "Огнемёд",
        cost: {
            materials: 45900,
            quartz: 90,
            generators: 75,
            microchip: 5,
        },
        amount: 49,
        place: "🛠Верстак",
    },
    {
        icon: "☄",
		title: "️Больверизатор",
        cost: {
            materials: 59990,
            quartz: 100,
            generators: 90,
            microchip: 45,
        },
        amount: 56,
        place: "🛠Верстак",
    },
    {
        icon: "🔮",
		title: "Энергосфера",
        cost: {
            materials: 78990,
            generators: 120,
            microchip: 60,
            iridium: 20,
        },
        amount: 65,
        place: "🛠Верстак",
    },
    {
        icon: "🌟",
		title: "Армагеддец",
        cost: {
            materials: 129990,
            generators: 150,
            microchip: 70,
            iridium: 40,
        },
        amount: 79,
        place: "🛠Верстак",
    }
];